language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install
  - ./bin/jackrabbit.sh
  - php bin/jackrabbit.php

script: phpunit --coverage-text

notifications:
  irc: "irc.freenode.org#sulu-cmf"

matrix:
  allow_failures:
    - php: hhvm
