language: php

php:
  - 5.4
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install
  - ./bin/jackrabbit.sh
  - php bin/jackrabbit.php
  - ./bin/runtests.sh

script: phpunit --coverage-text

matrix:
  allow_failures:
    - php: hhvm
