sudo: false

language: php

php:
  - 5.5
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install  --prefer-dist --no-interaction
  - ./bin/jackrabbit.sh

script: 
  # launch with the "r" flag in order to restart jackrabbit after each suite
  # see: https://github.com/sulu-io/sulu/issues/2137
  - time ./bin/runtests.sh -i -a -r
  - phpunit

notifications:
  slack:
    secure: "Gd3/1e0pBKvJv1UhWpBkWijJpmSWlarg6uPBJO0h4z1IpkZjd++jOjhmOQ7n+yMfuapQuJTcVOK0yIWu7orJoGAKFkBlMEIrLk1xMAG9phjjMLUO0FWgcQ3eVW5mTyfMBtClz4OL5wXckw17ohtXHDK8qnI0Hz9Qj8Rqgf2OZhM="

