sulu_translate:
    resource: "@SuluTranslateBundle/Resources/config/routing_api.yml"
    prefix: /api

sulu_translate.template.catalogue.form:
    path: /template/catalogue/form
    defaults:
        _controller: SuluTranslateBundle:Template:catalogueform
