sulu_translate:
    type: rest
    resource: "@SuluTranslateBundle/Resources/config/routing_api.yml"
    prefix: /api

sulu_translate.template.catalogue.form:
    path: /template/package/form
    defaults:
        _controller: SuluTranslateBundle:Template:packageform

sulu_translate.template.code.form:
     path: /template/translation/form
     defaults:
         _controller: SuluTranslateBundle:Template:translationform

sulu_translate.template.package.list:
     path: /template/package/list
     defaults:
         _controller: SuluTranslateBundle:Template:packagelist