parameters:
    sulu_translate.admin.class: Sulu\Bundle\TranslateBundle\Admin\TranslateAdmin

services:
    sulu_translate.admin:
        class: %sulu_translate.admin.class%
        tags:
            - { name: sulu.admin }