language: php

php:
  - 5.4

before_script:
  - composer install --dev
  - ./vendor/sulu/test-bundle/Sulu/Bundle/TestBundle/Resources/bin/travis.sh

script: phpunit --process-isolation --coverage-text
