language: php

php:
  - 5.4

env:
  - SYMFONY_VERSION=2.4.*

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION}
  - Tests/bin/travis.sh

script: phpunit --coverage-text

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master

