Sulu\Bundle\TranslateBundle\Entity\Catalogue:
    type: entity
    table: tr_catalogues
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        locale:
            type: string
            length: '60'
    oneToMany:
        translations:
            targetEntity: Translation
            mappedBy: catalogue
    manyToOne:
        package:
            targetEntity: Package
            inversedBy: tr_packages
            joinColumn:
                name: idPackages
                referencedColumnName: id
                nullable: false
    lifecycleCallbacks: {  }
