Sulu\Bundle\TranslateBundle\Entity\Code:
    type: entity
    repositoryClass: Sulu\Bundle\TranslateBundle\Entity\CodeRepository
    table: tr_codes
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: '60'
        backend:
            type: boolean
        frontend:
            type: boolean
        length:
            type: integer
            nullable: true
    manyToOne:
        package:
            targetEntity: Package
            inversedBy: codes
            joinColumn:
                name: idPackages
                referencedColumnName: id
                nullable: false
        location:
            targetEntity: Location
            inversedBy: codes
            joinColumn:
                name: idLocations
                referencedColumnName: id
    oneToMany:
        translations:
            targetEntity: Translation
            mappedBy: code
            cascade: [remove]
    lifecycleCallbacks: {  }
