Sulu\Bundle\TranslateBundle\Entity\Location:
    type: entity
    table: tr_locations
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: '60'
    oneToMany:
        codes:
            targetEntity: Code
            mappedBy: location
    manyToOne:
        package:
            targetEntity: Package
            inversedBy: tr_packages
            joinColumn:
                name: idPackages
                referencedColumnName: id
                nullable: false
    lifecycleCallbacks: {  }
