Sulu\Bundle\TranslateBundle\Entity\Package:
    type: entity
    table: tr_packages
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: '60'
    oneToMany:
        codes:
            targetEntity: Code
            mappedBy: package
            cascade: [remove]
        locations:
            targetEntity: Location
            mappedBy: package
            cascade: [remove]
        catalogues:
            targetEntity: Catalogue
            mappedBy: package
            cascade: [remove]
    lifecycleCallbacks: {  }
